name: Get Last Commit

on:
  workflow_dispatch:  # 手动触发器
  push:
    branches: [ main ]
    # repositories:
    #   - W1ndys/Easy-QFNU
      
permissions:
  contents: write
  
jobs:

  get-last-commit:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      # with:
      #   repository: W1ndys/Easy-QFNU
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: python -m pip install requests
    - name: Get last commit
      run: python get-last-commit.py
    - name: Commit and push index.html
      run: |
        git config --global user.email "w1ndys@outlook.com"
        git config --global user.name "W1ndys"
        git add index.html
        git commit -m "Update index.html with last commit info"
        git push
